### ISSUE TITLE
When alt-tabbing out of the game, spams the L# console

### ISSUE THREAD

**Issue by niktamerfdp** [HoesLeaguesharp/LeagueSharp#5]
Whenever I alt-tab out of the main LoL window, the L# console gets spammed of "Object reference not set to an instance of an object. at Slutty_ryze.Program.Game_OnUpdate(EventArgs args) at LeagueSharp.Game.OnUpdateNative())"

Sometimes causes the game to crash (League of Legends caused ACCESS_VIOLATION in module League of Legends

Write to location 00000000 caused an access violation.)

**Comment by HyunMi027** [comment]
mkay
